stages:
  - scan
  - build

secret_scan:
  stage: scan

  image:
    name: zricethezav/gitleaks:latest
    entrypoint: [""]

  script:
    - gitleaks detect --source . --verbose

build:
  stage: build

  image: eclipse-temurin:21

  script:
    - chmod +x mvnw
    - ./mvnw clean package

  artifacts:
    paths:
      - target/*.jar
