name: Build, Test and SAST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: eclipse-temurin:21

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Build, test and package
        run: ./mvnw clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: target/*.jar

  sast:
    needs: build

    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: semgrep scan --config auto --sarif --output semgrep.sarif

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

      - name: Upload Semgrep artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep.sarif

  sca:
    needs: build

    runs-on: ubuntu-latest

    container:
      image: maven:3.9.6-eclipse-temurin-21

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run OWASP Dependency Check
        run: mvn org.owasp:dependency-check-maven:check -DautoUpdate=false -DfailOnError=false

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html
  dast-baseline:
    needs: build

    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: built-jar
          path: target

      - name: Start application
        run: |
          java -jar target/*.jar &
          sleep 60

      - name: Create empty ZAP rules file
        run: touch zap-rules.tsv

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:8080'
          rules_file_name: 'zap-rules.tsv'

      - name: Upload ZAP Baseline Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-baseline-report
          path: report_html.html

  dast-api:
    needs: build

    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: built-jar
          path: target

      - name: Start application
        run: |
          java -jar target/*.jar &
          sleep 60

      - name: Run OWASP ZAP API Scan
        uses: zaproxy/action-api-scan@v0.8.0
        with:
          target: 'http://localhost:8080/v3/api-docs'

      - name: Upload ZAP API Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-api-report
          path: report_html.html
