name: Build, Test and SAST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: eclipse-temurin:21

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Build, test and package
        run: ./mvnw clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: target/*.jar

  sast:
    needs: build

    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: semgrep scan --config auto --sarif --output semgrep.sarif

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

      - name: Upload Semgrep artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep.sarif

  sca:
    needs: build

    runs-on: ubuntu-latest

    container:
      image: maven:3.9.6-eclipse-temurin-21

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run OWASP Dependency Check
        run: mvn org.owasp:dependency-check-maven:check -Dnvd.validForHours=24

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html
